"""add_rpe_description_to_series

Revision ID: 0314025adde5
Revises: da362c42feee
Create Date: 2026-01-02 12:16:45.392159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0314025adde5'
down_revision: Union[str, Sequence[str], None] = 'da362c42feee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainingseries', sa.Column('rpe_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainingseries', 'rpe_description')
    # ### end Alembic commands ###
