"""update_parent_session_fk_ondelete

Revision ID: 06d10f738efa
Revises: 0314025adde5
Create Date: 2026-01-02 17:58:42.858870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06d10f738efa'
down_revision: Union[str, Sequence[str], None] = '0314025adde5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainingsession', schema=None) as batch_op:
        batch_op.drop_constraint('fk_trainingsession_parent', type_='foreignkey')
        batch_op.create_foreign_key('fk_trainingsession_parent_new', 'trainingsession', ['parent_session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainingsession', schema=None) as batch_op:
        batch_op.drop_constraint('fk_trainingsession_parent_new', type_='foreignkey')
        batch_op.create_foreign_key('fk_trainingsession_parent', 'trainingsession', ['parent_session_id'], ['id'])
    # ### end Alembic commands ###
