"""update_parent_session_fk_ondelete

Revision ID: 06d10f738efa
Revises: 0314025adde5
Create Date: 2026-01-02 17:58:42.858870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06d10f738efa'
down_revision: Union[str, Sequence[str], None] = '0314025adde5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_trainingsession_parent'), 'trainingsession', type_='foreignkey')
    op.create_foreign_key(None, 'trainingsession', 'trainingsession', ['parent_session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trainingsession', type_='foreignkey')
    op.create_foreign_key(op.f('fk_trainingsession_parent'), 'trainingsession', 'trainingsession', ['parent_session_id'], ['id'])
    # ### end Alembic commands ###
