"""Add ConfigAthleteCategory table

Revision ID: 309d8451ed9f
Revises: 3be875b448b6
Create Date: 2026-01-07 17:02:48.492594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '309d8451ed9f'
down_revision: Union[str, Sequence[str], None] = '3be875b448b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configathletecategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_configathletecategory_id'), 'configathletecategory', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configathletecategory_id'), table_name='configathletecategory')
    op.drop_table('configathletecategory')
    # ### end Alembic commands ###
