"""Add parent_session_id

Revision ID: bad5db08f27e
Revises: 8f0dc6cddb18
Create Date: 2025-12-31 11:39:31.884739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad5db08f27e'
down_revision: Union[str, Sequence[str], None] = '8f0dc6cddb18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainingsession', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_session_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_trainingsession_parent', 'trainingsession', ['parent_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainingsession', schema=None) as batch_op:
        batch_op.drop_constraint('fk_trainingsession_parent', type_='foreignkey')
        batch_op.drop_column('parent_session_id')
    # ### end Alembic commands ###
