"""Add functional_base to subdivision

Revision ID: da362c42feee
Revises: bad5db08f27e
Create Date: 2026-01-02 07:47:12.022399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da362c42feee'
down_revision: Union[str, Sequence[str], None] = 'bad5db08f27e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainingsubdivision', sa.Column('functional_base', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainingsubdivision', 'functional_base')
    # ### end Alembic commands ###
